
<?php if($this->getCollection()->getSize()): ?>
<div class="toolbar">
    
	<div class="sorter">
		
		<p class="view-mode">
			<?php $_modes = $this->getModes(); ?>
			<?php if($_modes && count($_modes)>1): ?>
				<label><?php echo $this->__('View as') ?></label>
				<?php foreach ($this->getModes() as $_code=>$_label): ?>
					<?php if($this->isModeActive($_code)): ?>
						<strong title="<?php echo $_label ?>" class="<?php echo strtolower($_code); ?>"><?php echo $_label ?></strong>
					<?php else: ?>
						<a href="<?php echo $this->getModeUrl($_code) ?>" title="<?php echo $_label ?>" class="<?php echo strtolower($_code); ?>"><?php echo $_label ?></a>
					<?php endif; ?>
				<?php endforeach; ?>
			<?php endif; ?>
		</p>		

	</div>
    
    <div class="pager">
        <div class="count-container">
            <?php if($this->getLastPageNum()>1): ?>
                <p class="amount amount--has-pages">
                    <?php echo $this->__('%s-%s of %s', $this->getFirstNum(), $this->getLastNum(), $this->getTotalNum()) ?>
                </p>
            <?php else: ?>
                <p class="amount amount--no-pages">
                    <strong><?php echo $this->__('%s Item(s)', $this->getTotalNum()) ?></strong>
                </p>
            <?php endif; ?>

         
        </div>


    </div>
</div>
<?php endif ?>
